[package]
name = "prc-rs"
version = "1.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>", "jam1garner <jam1.mcleod@hotmail.com>"]
description = "Library for working with PRC types in Smash Ultimate"
license = "MIT"
repository = "https://github.com/ultimate-research/prc-rs"
edition = "2018"

[lib]
name = "prc"
path = "src/lib/lib.rs"

[[bin]]
name = "param-xml"
path = "src/param-xml/main.rs"
required-features = ["main"]

[features]
default = ["main"]
xml = ["quick-xml"]
main = ["xml", "structopt"]

[dependencies]
byteorder = "^1.3"
hash40 = "^0.4.3"
indexmap = "^1.2"
quick-xml = { version = "^0.18.1", optional = true }
serde = { version = "^1", features = ["derive"] }
structopt = { version = "^0.3", optional = true }